const database = {
    "Plats Tunisiens": [
        { name: "Brik à l'œuf (frit)", carb: 20 },
        { name: "Brik au thon (frit)", carb: 20 },
        { name: "Chakchouka", carb: 7 },
        { name: "Chorba", carb: 12 },
        { name: "Couscous à la viande", carb: 28 },
        { name: "Couscous au poisson", carb: 28 },
        { name: "Couscous aux légumes", carb: 25 },
        { name: "Fricassé", carb: 35 },
        { name: "Kamounia", carb: 4 },
        { name: "Kefteji", carb: 8 },
        { name: "Lablabi (sans pain)", carb: 18 },
        { name: "Makarouna (Pâtes sauce)", carb: 28 },
        { name: "Marka (Ragoût)", carb: 6 },
        { name: "Merguez", carb: 1 },
        { name: "Mloukhia", carb: 7 },
        { name: "Mosli (Poisson/Poulet)", carb: 6 },
        { name: "Ojja", carb: 6 },
        { name: "Riz Djerbien", carb: 26 },
        { name: "Salade tunisienne", carb: 4 },
        { name: "Slata Méchouia", carb: 5 },
        { name: "Sohleb", carb: 25 },
        { name: "Tajine Tunisien", carb: 8 }
    ],
    "Féculents & Plats": [
        { name: "Frites (100g)", carb: 35 },
        { name: "Lentilles / Haricots secs (cuits)", carb: 15 },
        { name: "Maïs / Petits pois", carb: 20 },
        { name: "Pain (Baguette/Mie)", carb: 50 },
        { name: "Pain complet/Céréales", carb: 45 },
        { name: "Biscottes", carb: 70 },
        { name: "Pâtes / Riz / Semoule (CUITS)", carb: 30 },
        { name: "Pizza (pâte fine)", carb: 30 },
        { name: "Pomme de terre (cuite eau/vapeur)", carb: 20 },
        { name: "Purée", carb: 15 },
        { name: "Quiche (1 part)", carb: 20 },
        { name: "Sandwich (Baguette classique)", carb: 50 }
    ],
    "Fruits": [
        { name: "Abricot frais", carb: 9 }, 
        { name: "Ananas", carb: 11 },
        { name: "Banane", carb: 20 },
        { name: "Cerises", carb: 12 },
        { name: "Clémentine / Mandarine", carb: 10 },
        { name: "Compote (sans sucre ajouté)", carb: 12 },
        { name: "Compote (sucrée)", carb: 20 },
        { name: "Dattes / Fruits secs", carb: 65 },
        { name: "Figues fraîches", carb: 16 },
        { name: "Fraises / Framboises", carb: 7 },
        { name: "Kiwi", carb: 11 },
        { name: "Melon", carb: 7 },
        { name: "Orange", carb: 9 },
        { name: "Pamplemousse", carb: 7 },
        { name: "Pastèque", carb: 7 },
        { name: "Pêche / Nectarine", carb: 10 },
        { name: "Poire", carb: 11 },
        { name: "Pomme", carb: 12 },
        { name: "Prunes", carb: 10 },
        { name: "Raisin frais", carb: 17 }
    ],
    "Desserts & Sucreries": [
        { name: "Assida Zgougou", carb: 40 },
        { name: "Barre de céréales", carb: 65 },
        { name: "Biscuits secs / Sablés", carb: 70 },
        { name: "Brioche", carb: 50 },
        { name: "Bsissa", carb: 60 },
        { name: "Chocolat (Noir ou Lait)", carb: 50 },
        { name: "Confiture / Miel", carb: 75 },
        { name: "Crêpe (nature)", carb: 25 },
        { name: "Croissant / Pain au choc", carb: 45 },
        { name: "Glace / Sorbet", carb: 25 },
        { name: "Makroudh", carb: 65 },
        { name: "Tarte aux fruits", carb: 45 },
        { name: "Yaourt aux fruits", carb: 14 },
        { name: "Yaourt nature", carb: 5 }
    ],
    "Boissons": [
        { name: "Jus de fruits (100% ou commerce)", carb: 12 },
        { name: "Soda (Coca, etc.)", carb: 11 },
    ]
};
