const database = {
    "Plats Tunisiens": [
        { name: "Brik", carb: 20 },
        { name: "Chakchouka", carb: 7 },
        { name: "Chorba", carb: 12 },
        { name: "Couscous", carb: 28 },
        { name: "Fricassé", carb: 35 },
        { name: "Kamounia", carb: 4 },
        { name: "Kefteji", carb: 8 },
        { name: "Lablabi", carb: 18 },
        { name: "Makarouna", carb: 28 },
        { name: "Marka", carb: 6 },
        { name: "Merguez", carb: 1 },
        { name: "Mloukhia", carb: 7 },
        { name: "Mosli", carb: 6 },
        { name: "Ojja", carb: 6 },
        { name: "Riz Djerbien", carb: 26 },
        { name: "Salade tunisienne", carb: 4 },
        { name: "Slata Méchouia", carb: 5 },
        { name: "Sohleb", carb: 25 },
        { name: "Tajine tunisien", carb: 8 }
    ],
    "Féculents & Plats": [
        { name: "Frites", carb: 35 },
        { name: "Haricots secs (cuits)", carb: 15 },
        { name: "Lentilles (cuits)", carb: 15 },
        { name: "Petits pois", carb: 20 },
        { name: "Maïs", carb: 20 },
        { name: "Pain de mie)", carb: 50 },
        { name: "Pain baguette", carb: 50 },
        { name: "Pain complet/Céréales", carb: 45 },
        { name: "Biscottes", carb: 70 },
        { name: "Pâtes (cuits)", carb: 30 },
        { name: "Riz (cuits)", carb: 30 },
        { name: "Semoule (cuits)", carb: 30 },
        { name: "Pizza (pâte fine)", carb: 30 },
        { name: "Pomme de terre (cuite eau/vapeur)", carb: 20 },
        { name: "Purée", carb: 15 },
        { name: "Quiche", carb: 20 },
        { name: "Sandwich (Pain baguette)", carb: 50 }
    ],
    "Fruits": [
        { name: "Abricot frais", carb: 9 }, 
        { name: "Ananas", carb: 11 },
        { name: "Banane", carb: 20 },
        { name: "Cerises", carb: 12 },
        { name: "Clémentine", carb: 10 },
        { name: "Mandarine", carb: 10 },
        { name: "Compote (sans sucre ajouté)", carb: 12 },
        { name: "Compote (sucrée)", carb: 20 },
        { name: "Dattes", carb: 65 },
        { name: "Fruits secs", carb: 65 },
        { name: "Figues fraîches", carb: 16 },
        { name: "Fraises", carb: 7 },
        { name: "Framboises", carb: 7 },
        { name: "Kiwi", carb: 11 },
        { name: "Melon", carb: 7 },
        { name: "Orange", carb: 9 },
        { name: "Pamplemousse", carb: 7 },
        { name: "Pastèque", carb: 7 },
        { name: "Pêche", carb: 10 },
        { name: "Nectarine", carb: 10 },
        { name: "Poire", carb: 11 },
        { name: "Pomme", carb: 12 },
        { name: "Prunes", carb: 10 },
        { name: "Raisin", carb: 17 }
    ],
    "Desserts & Sucreries": [
        { name: "Assida Zgougou", carb: 40 },
        { name: "Barre de céréales", carb: 65 },
        { name: "Biscuits secs", carb: 70 },
        { name: "Sablés", carb: 70 },
        { name: "Brioche", carb: 50 },
        { name: "Bsissa", carb: 60 },
        { name: "Chocolat (Noir ou Lait)", carb: 50 },
        { name: "Confiture", carb: 75 },
        { name: "Miel", carb: 75 },
        { name: "Crêpe (nature)", carb: 25 },
        { name: "Croissant", carb: 45 },
        { name: "Pain au chocolat", carb: 45 },
        { name: "Glace", carb: 25 },
        { name: "Makroudh", carb: 65 },
        { name: "Tarte aux fruits", carb: 45 },
        { name: "Yaourt aux fruits", carb: 14 },
        { name: "Yaourt nature", carb: 5 }
    ],
    "Boissons": [
        { name: "Jus de fruits", carb: 12 },
        { name: "Soda", carb: 11 },
    ]
};
